# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

c_cov2cor <- function(m) {
    .Call('mvtraits_c_cov2cor', PACKAGE = 'mvtraits', m)
}

c_sample_mvnorm_hier <- function(niter, dat, groups, mu_global, Sigma_global, mu_group, Sigma_group, mu0_global, Sigma0_global_inv, mu0_group, Sigma0_group_inv, v0_global, S0_global, v0_group, S0_group, setup_bygroup) {
    .Call('mvtraits_c_sample_mvnorm_hier', PACKAGE = 'mvtraits', niter, dat, groups, mu_global, Sigma_global, mu_group, Sigma_group, mu0_global, Sigma0_global_inv, mu0_group, Sigma0_group_inv, v0_global, S0_global, v0_group, S0_group, setup_bygroup)
}

c_sample_mvnorm <- function(niter, dat, mu, Sigma, mu0, Sigma0_inv, v0, S0, setup) {
    .Call('mvtraits_c_sample_mvnorm', PACKAGE = 'mvtraits', niter, dat, mu, Sigma, mu0, Sigma0_inv, v0, S0, setup)
}

c_mvnorm_fill_missing <- function(dat, mu, Sigma, setup) {
    .Call('mvtraits_c_mvnorm_fill_missing', PACKAGE = 'mvtraits', dat, mu, Sigma, setup)
}

c_random_mvnorm <- function(n, mu, Sigma) {
    .Call('mvtraits_c_random_mvnorm', PACKAGE = 'mvtraits', n, mu, Sigma)
}

rwishart <- function(df, S) {
    .Call('mvtraits_rwishart', PACKAGE = 'mvtraits', df, S)
}

set_R_seed <- function() {
    invisible(.Call('mvtraits_set_R_seed', PACKAGE = 'mvtraits'))
}

