# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mvnorm_fill_missing <- function(y, mu, Sigma_chol) {
    .Call('mvtraits_mvnorm_fill_missing', PACKAGE = 'mvtraits', y, mu, Sigma_chol)
}

scatter <- function(mat) {
    .Call('mvtraits_scatter', PACKAGE = 'mvtraits', mat)
}

